spring.application.name=backend


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/devpilot}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.f=driver-class-name:org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8081

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.embedding.model=text-embedding-3-small

#Github Oauth2
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:}
spring.security.oauth2.client.registration.github.scope=read:user,repo
spring.security.oauth2.client.provider.github.user-name-attribute=id

server.servlet.session.cookie.name=DEVPILOT_SESSION
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.timeout=7d

#App settings

# for now open-ai is disable to run application

#spring.autoconfigure.exclude=\
#  org.springframework.ai.model.openai.autoconfigure.OpenAiAutoConfiguration,\
#  org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration,\
#  org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration,\
#  org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration,\
#  org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration,\
#  org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration